CREATE TABLE IF NOT EXISTS public.ubicacion_geografica
(
    id_ubicacion integer NOT NULL,
    comuna character varying(255) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    region character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT ubicacion_geografica_pkey PRIMARY KEY (id_ubicacion)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ubicacion_geografica
    OWNER to postgres;
	
CREATE TABLE IF NOT EXISTS public.empresa
(
    id_empresa integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_empresa character varying(255) COLLATE pg_catalog."default" NOT NULL,
    restriccion_edad integer,
    id_ubicacion integer,
    CONSTRAINT empresa_pkey PRIMARY KEY (id_empresa),
    CONSTRAINT uk_fawbrfb4c2062dbtpiqxf882b UNIQUE (nombre_empresa),
    CONSTRAINT fktfycib32lgjra3htpv4g294wr FOREIGN KEY (id_ubicacion)
        REFERENCES public.ubicacion_geografica (id_ubicacion) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.empresa
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.rol
(
    id integer NOT NULL,
    alias_rol character varying(255) COLLATE pg_catalog."default",
    nombre_rol character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT rol_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.rol
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario integer NOT NULL,
    apellido_usuario character varying(255) COLLATE pg_catalog."default",
    contrasena character varying(255) COLLATE pg_catalog."default",
    correo character varying(255) COLLATE pg_catalog."default",
    fecha_nacimiento character varying(255) COLLATE pg_catalog."default",
    nombre_usuario character varying(255) COLLATE pg_catalog."default",
    id_ubicacion integer,
    id_rol integer,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT fk1orsvgjxg16y1sggtq56fdpnh FOREIGN KEY (id_rol)
        REFERENCES public.rol (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkil9wms4dg34jfsukomvjoqi6n FOREIGN KEY (id_ubicacion)
        REFERENCES public.ubicacion_geografica (id_ubicacion) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.empresas_favoritas
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    favorito boolean NOT NULL,
    id_empresa integer,
    id_usuario integer,
    CONSTRAINT empresas_favoritas_pkey PRIMARY KEY (id),
    CONSTRAINT fk58p96l7u9tevdtb1hom8ua0ch FOREIGN KEY (id_empresa)
        REFERENCES public.empresa (id_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkn8ssk89l99fh4kus41xo2qbop FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.empresas_favoritas
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.carrito_compras
(
    id_carrito integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_usuario integer,
    CONSTRAINT carrito_compras_pkey PRIMARY KEY (id_carrito),
    CONSTRAINT fku668eyf82dctdn4gurx8y2bt FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.carrito_compras
    OWNER to postgres;
	

CREATE TABLE IF NOT EXISTS public.tipo_producto
(
    id_tipo_producto integer NOT NULL,
    nombre_tipo character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tipo_producto_pkey PRIMARY KEY (id_tipo_producto)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tipo_producto
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.producto
(
    id_producto integer NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    nombre_producto character varying(255) COLLATE pg_catalog."default",
    precio real,
    stock integer,
    tipo character varying(255) COLLATE pg_catalog."default",
    ventas_producto integer,
    CONSTRAINT producto_pkey PRIMARY KEY (id_producto)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.producto
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.valoracion
(
    id_valoracion integer NOT NULL,
    comentario character varying(255) COLLATE pg_catalog."default",
    estrellas integer,
    nombre_empresa character varying(255) COLLATE pg_catalog."default",
    id_empresa integer,
    id_usuario integer,
    CONSTRAINT valoracion_pkey PRIMARY KEY (id_valoracion),
    CONSTRAINT fk6d4ybhl7h0cqgwss25s5q24xh FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkclpy8nw3q1f14nufsiywi978e FOREIGN KEY (id_empresa)
        REFERENCES public.empresa (id_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.valoracion
    OWNER to postgres;
	
CREATE TABLE IF NOT EXISTS public.empresa_producto
(
    id_empresa integer NOT NULL,
    id_producto integer NOT NULL,
    CONSTRAINT empresa_producto_pkey PRIMARY KEY (id_empresa, id_producto),
    CONSTRAINT fk8eit9txdcj7u918kj6fcox4nc FOREIGN KEY (id_producto)
        REFERENCES public.producto (id_producto) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkhrclyon6mdt3w62ry47q35mf3 FOREIGN KEY (id_empresa)
        REFERENCES public.empresa (id_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.empresa_producto
    OWNER to postgres;
	
CREATE TABLE IF NOT EXISTS public.carrito_compras_producto
(
    id_carrito_producto integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cantidad integer,
    id_carrito integer,
    id_producto integer,
    CONSTRAINT carrito_compras_producto_pkey PRIMARY KEY (id_carrito_producto),
    CONSTRAINT fk15voie3e2nl3t9mo9hcdbdh5p FOREIGN KEY (id_carrito)
        REFERENCES public.carrito_compras (id_carrito) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk4ruqxrefyw2557cl4iiq3oocx FOREIGN KEY (id_producto)
        REFERENCES public.producto (id_producto) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.carrito_compras_producto
    OWNER to postgres;
	
CREATE TABLE IF NOT EXISTS public.empresa_tipo_producto
(
    id_empresa integer NOT NULL,
    id_tipo_producto integer NOT NULL,
    CONSTRAINT empresa_tipo_producto_pkey PRIMARY KEY (id_empresa, id_tipo_producto),
    CONSTRAINT fk6uvgvdrhkbvclkibnktic11vy FOREIGN KEY (id_empresa)
        REFERENCES public.empresa (id_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkesanp18jy3w8equqr5ie0qxf FOREIGN KEY (id_tipo_producto)
        REFERENCES public.tipo_producto (id_tipo_producto) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.empresa_tipo_producto
    OWNER to postgres;



CREATE TABLE IF NOT EXISTS public.metodo_pago
(
    id integer NOT NULL,
    metodo_pago character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT metodo_pago_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.metodo_pago
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago integer NOT NULL,
    monto real,
    id_usuario integer,
    metodo_pago integer,
    CONSTRAINT pago_pkey PRIMARY KEY (id_pago),
    CONSTRAINT fkhav0n6gtpnpf7m6cxf7cjniom FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkmwkmcmd19xn2mrbk6i5epg09d FOREIGN KEY (metodo_pago)
        REFERENCES public.metodo_pago (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pago
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.permiso
(
    id integer NOT NULL,
    permiso character varying(255) COLLATE pg_catalog."default",
    id_rol integer,
    CONSTRAINT permiso_pkey PRIMARY KEY (id),
    CONSTRAINT fk9404i0nx83n8c0cxskbg59rx8 FOREIGN KEY (id_rol)
        REFERENCES public.rol (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.permiso
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.usuario_producto
(
    id_usuario integer NOT NULL,
    id_producto integer NOT NULL,
    CONSTRAINT usuario_producto_pkey PRIMARY KEY (id_usuario, id_producto),
    CONSTRAINT fk5fq8xx0p01h38daum7248hq7j FOREIGN KEY (id_producto)
        REFERENCES public.producto (id_producto) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkaoif9yeyeup5gpdwavqsxcg1j FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario_producto
    OWNER to postgres;
